markdown: redcarpet

release_version: "2.0"

description: "Tabster is a free, open-source application that allows you to easily create, organize, search, edit, view, and print ASCII tablature for guitar, bass, drums and more."

google_analytics: UA-42796771-1

changelog:
  - 
    version: "2.0"
    date: "-"
    changes:
        - "Changed: SQLite used for library/playlists/recent items"
        - "Changed: XML file format to binary"
        - "Added: Portable mode"
        - "Added: Proxy settings"
        - "Added: Application-specific printing format"
        - "Added: XML importing/exporting"
        - "Added: HTML importing/exporting"
        - "Added: RTF importing/exporting"
        - "Added: PNG exporting"
        - "Added: PDF importing/exporting"
        - "Added: HTML file exporting"
        - "Added: Rating search filter"
        - "Added: Songsterr support"
        - "Added: Guitartabs.cc support"
        - "Added: Search suggestions"
        - "Added: Ukulele tablature support"
        - "Added: Plugin system"
        - "Fixed: Bug on startup displaying message box when no updates are available"
        - "Changed: Major UI modifications"
        - "Changed: Major codebase refactoring"
  -
    version: "1.6"
    date: "August 28th, 2013"
    changes:
        - "Added: Downloads sub-library"
        - "Added: Auto-scrolling"
        - "Added: Single-instance functionality"
        - "Added: Persistent window size/state"
        - "Added: Preview pane to library and search"
        - "Changed: Tablature file format"
        - "Added: Forced caching"
        - "Removed: auto-detect"
        - "Removed: Embedded web browser"
        - "Fixed: Various search bugs"
        - "Added: Multi-downloader"
        - "Changed: Minor UI modifications"
        - "Changed: Major codebase refactoring"
  -
    version: "1.5.1"
    date: "June 7th, 2011"
    changes:
        - "Fixed: Bug with library search filter remaining when library is scanned"
        - "Added: Tablature repair to fix missing XML declarations"
        - "Added: Corrupt file detection"
        - "Added: Option to open downloaded/imported tabs after saving"
        - "Added: Option to open source URL of tabs in library"
        - "Added: Option to search for similar tabs from library"
        - "Fixed bug when clearing library search"
        - "Added: Search feature"
  -
    version: "1.5"
    date: "June 3rd, 2011"
    changes:
        - "Changed: Deleted tabs are now sent to the recycle bin"
        - "Fixed: Bug with newly created tabs not opening"
        - "Fixed: Bug with file associations"
        - "Added: File association for Tabster playlists"
        - "Changed: Warning dialog when closing unsaved tabs to display titles for every unsaved tab"
        - "Added: Menu options to show/hide side panel and status bar"
        - "Changed: Filter is now reset when switching sub-libraries"
        - "Added: Library cache for faster startup. (optional)"
        - "Removed: Multiple directory support in favor of central directory"
        - "Added: Save dialog when saving new tab online"
        - "Changed:Exporting now supports exporting to either text (.txt) or Tabster (.tabster) file"
        - "Added: Playlists"
        - "Changed: Recent files storage from registory to XML"
        - "Changed: File-naming convention now includes the tablature type to help avoid possible filename collisions"
        - "Changed: Tablature file format to include view count, rating, and difficulty"
        - "Added: Middle click to open library items"
        - "Removed: Error log viewer"
        - "Fixed: Bug when creating new tab and it staying in temporary folder"
        - "Fixed: Bug with improper date sorting"
        - "Added: NSIS-based installer"
        - "Added: Tabbed interface to tab viewer"
        - "Changed: Minor UI modifications"
        - "Changed: Major codebase refactoring"
  -
    version: "1.1"
    date: "January 15th, 2011"
    changes:
        - "Changed: Minor UI modifications"
        - "Fixed: Bug with persistent saving when closing a newly created tab"
        - "Fixed: Bug when re-scanning library while filter is set"
        - "Fixed: Library not updating properly when tabs modified/deleted"
        - "Added: Favorites option in information dialog"
        - "Added: Download utility"
        - "Added: Error log viewer"
        - "Added: Sublibraries for imported tabs, guitar tabs, guitar chords, bass tabs, drum tabs, and favorites"
  -
    version: "1.0.3"
    date: "January 7th, 2011"
    changes:
        - "Fixed: Connection timeout when checking for updates"
        - "Changed: Minor UI modifications"
        - "Added: Error logging"
  -
    version: "1.0"
    date: "January 6th, 2011"
    changes:
        - "Initial release"

faqs:
  -
    question: I found a bug, where do I report it?
    answer: Use the <a href="https://github.com/NateShoffner/Tabster/issues" target="_blank">issue tracker</a> to report any bugs..
  -
    question: How do I install plugins?
    answer: Plugins are placed in the 'Plugins' directory, located in your installation directory. Subdirectories are fine, as long as they are nested within the 'Plugins' directory.
  -
    question: Can I run Tabster on Mac/Linux?
    answer: Currently, Tabster is not 100% Mono-compliant. This may change in the future however.
  -
    question: How do I create plugins?
    answer: Plugins can be created using any .NET language by referencing the appropriate assemblies. See the <a href="#plugins">plugins</a> section for more information.
  -
    question: What sites/archives able to be searched?
    answer: Natively, Ultimate Guitar, Guitartabs.cc, and Songsterr are supported with more to likely be added in the future.