name: "Tabster"
title: "Tabster"
markdown: redcarpet
permalink: /:title/

release_version: "2.0"

google_analytics: UA-42796771-1

changelog:
 - version: "2.0"
 - changes:
    - change: "Changed: SQLite used for library/playlists/recent items"
    - change: "Changed: XML file format to binary"
    - change: "Added: Portable mode"
    - change: "Added: Proxy settings"
    - change: "Added: Application-specific printing format"
    - change: "Added: XML importing/exporting"
    - change: "Added: HTML importing/exporting"
    - change: "Added: RTF importing/exporting"
    - change: "Added: PNG exporting"
    - change: "Added: PDF importing/exporting"
    - change: "Added: HTML file exporting"
    - change: "Added: Rating search filter"
    - change: "Added: Songsterr support"
    - change: "Added: Guitartabs.cc support"
    - change: "Added: Search suggestions"
    - change: "Added: Ukulele tablature support"
    - change: "Added: Plugin system"
    - change: "Fixed: Bug on startup displaying message box when no updates are available"
    - change: "Changed: Major UI modifications"
    - change: "Changed: Major codebase refactoring"
 - version: "1.6"
 - changes:
    - change: "Added: Downloads sub-library"
    - change: "Added: Auto-scrolling"
    - change: "Added: Single-instance functionality"
    - change: "Added: Persistent window size/state"
    - change: "Added: Preview pane to library and search"
    - change: "Changed: Tablature file format"
    - change: "Added: Forced caching"
    - change: "Removed: auto-detect"
    - change: "Removed: Embedded web browser"
    - change: "Fixed: Various search bugs"
    - change: "Added: Multi-downloader"
    - change: "Changed: Minor UI modifications"
    - change: "Changed: Major codebase refactoring"
 - version: "1.5.1"
 - changes:
    - change: "Fixed: Bug with library search filter remaining when library is scanned"
    - change: "Added: Tablature repair to fix missing XML declarations"
    - change: "Added: Corrupt file detection"
    - change: "Added: Option to open downloaded/imported tabs after saving"
    - change: "Added: Option to open source URL of tabs in library"
    - change: "Added: Option to search for similar tabs from library"
    - change: "Fixed bug when clearing library search"
    - change: "Added: Search feature"
 - version: "1.5"
 - changes:
    - change: "Changed: Deleted tabs are now sent to the recycle bin"
    - change: "Fixed: Bug with newly created tabs not opening"
    - change: "Fixed: Bug with file associations"
    - change: "Added: File association for Tabster playlists"
    - change: "Changed: Warning dialog when closing unsaved tabs to display titles for every unsaved tab"
    - change: "Added: Menu options to show/hide side panel and status bar"
    - change: "Changed: Filter is now reset when switching sub-libraries"
    - change: "Added: Library cache for faster startup. (optional)"
    - change: "Removed: Multiple directory support in favor of central directory"
    - change: "Added: Save dialog when saving new tab online"
    - change: "Changed:Exporting now supports exporting to either text (.txt) or Tabster (.tabster) file"
    - change: "Added: Playlists"
    - change: "Changed: Recent files storage from registory to XML"
    - change: "Changed: File-naming convention now includes the tablature type to help avoid possible filename collisions"
    - change: "Changed: Tablature file format to include view count, rating, and difficulty"
    - change: "Added: Middle click to open library items"
    - change: "Removed: Error log viewer"
    - change: "Fixed: Bug when creating new tab and it staying in temporary folder"
    - change: "Fixed: Bug with improper date sorting"
    - change: "Added: NSIS-based installer"
    - change: "Added: Tabbed interface to tab viewer"
    - change: "Changed: Minor UI modifications"
    - change: "Changed: Major codebase refactoring"
 - version: "1.1"
 - changes:
    - change: "Changed: Minor UI modifications"
    - change: "Fixed: Bug with persistent saving when closing a newly created tab"
    - change: "Fixed: Bug when re-scanning library while filter is set"
    - change: "Fixed: Library not updating properly when tabs modified/deleted"
    - change: "Added: Favorites option in information dialog"
    - change: "Added: Download utility"
    - change: "Added: Error log viewer"
    - change: "Added: Sublibraries for imported tabs, guitar tabs, guitar chords, bass tabs, drum tabs, and favorites"
 - version: "1.0.3"
 - changes:
    - change: "Fixed: Connection timeout when checking for updates"
    - change: "Changed: Minor UI modifications"
    - change: "Added: Error logging"
 - version: "1.0"
 - changes:
    - change: "Initial release"


navigation:
- text: Home
  url: /
- text: Download
  url: /download/
- text: FAQ
  url: /faq/
- text: Plugins
  url: /plugins/
- text: Donate
  url: /donate/